### ISSUE TITLE
Wrong country displayed

### ISSUE THREAD

**Issue by Kowismo** [hakanensari/country#24]
Hello!

Since today every IP is currently shown as "FR", including mine and i'm from Germany.

**Comment by Kowismo** [comment]
Now all IP's from the User on my Teamspeak have an German IP.
I doesn't know what happened, but its very buggy.
Many are from Ukraine/Russia etc. and it shows as Germany.

**Comment by hakanensari** [comment]
@Kowismo, I introduced this bug today after moving the hosted API behind the Cloudflare proxy. It should be fixed now.
