### ISSUE TITLE
CURL - 404 et  Connection state changed (MAX_CONCURRENT_STREAMS == 250)!

### ISSUE THREAD

**Issue by r0m1CH** [hakanensari/country#41]
Bonjour,

Merci pour ce super projet. C'est le top.
Je l'utilise depuis quelques semaines dans un script pour me valider la provenance d'une IP (il doit y avoir 30 requetes jours je dirais).
Cela marchait bien jusque là mais plus trop ces jours. Je trouve pas le souci. Voici un example curl:

> curl -v  https://api.country.is/149.22.89.73
> *   Trying 0.0.0.0:443...
> * Connected to api.country.is (127.0.0.1) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> *  CAfile: /etc/ssl/certs/ca-certificates.crt
> *  CApath: /etc/ssl/certs
> * TLSv1.0 (OUT), TLS header, Certificate Status (22):
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS header, Certificate Status (22):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS header, Finished (20):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (OUT), TLS header, Unknown (21):
> * TLSv1.3 (OUT), TLS alert, unknown CA (560):
> * SSL certificate problem: self-signed certificate
> * Closing connection 0
> curl: (60) SSL certificate problem: self-signed certificate
> More details here: https://curl.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above_

Si je met --insecure, je me trouve avec une erreur 404 et Connection state changed (MAX_CONCURRENT_STREAMS == 250)! dans la nego SSL:

> curl -v --insecure  https://api.country.is/149.22.89.73
> *   Trying 0.0.0.0:443...
> * Connected to api.country.is (127.0.0.1) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * TLSv1.0 (OUT), TLS header, Certificate Status (22):
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS header, Certificate Status (22):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS header, Finished (20):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, CERT verify (15):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Finished (20):
> * TLSv1.2 (OUT), TLS header, Finished (20):
> * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * TLSv1.3 (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
> * ALPN, server accepted to use h2
> * Server certificate:
> *  subject: CN=TRAEFIK DEFAULT CERT
> *  start date: Sep 17 15:21:44 2024 GMT
> *  expire date: Sep 17 15:21:44 2025 GMT
> *  issuer: CN=TRAEFIK DEFAULT CERT
> *  SSL certificate verify result: self-signed certificate (18), continuing anyway.
> * Using HTTP2, server supports multiplexing
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * Using Stream ID: 1 (easy handle 0x55b97f8f6eb0)
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> > GET /149.22.89.73 HTTP/2
> > Host: api.country.is
> > user-agent: curl/7.81.0
> > accept: */*
> >
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> < HTTP/2 404
> < content-type: text/plain; charset=utf-8
> < x-content-type-options: nosniff
> < content-length: 19
> < date: Tue, 17 Sep 2024 15:25:51 GMT
> <
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> 404 page not found
> * Connection #0 to host api.country.is left intact

Une idée de ce que je fais mal ? 

Bonne journée
Romain

**Comment by hakanensari** [comment]
It seems you're hitting 127.0.0.1 instead of api.country.is. This could be due to a `/etc/hosts` entry perhaps?

**Comment by r0m1CH** [comment]
Yeah you are right. I didn't see it before your comment. My adguard protection seems to be the problem. Thanks for pointing out the right direction !
