### ISSUE TITLE
https://api.country.is is down

### ISSUE THREAD

**Issue by williamkhshea** [hakanensari/country#42]
https://api.country.is/ is down

![Screenshot 2024-09-27 at 1 54 59 AM](https://github.com/user-attachments/assets/a5ef8a61-b882-471a-a54d-e5425014dd2b)

**Comment by hakanensari** [comment]
I upgraded the server after a spike in usage. Things should be back to normal now. Let me know if you're still running into any issues.

**Comment by williamkhshea** [comment]
It's up and running now.
